FROM --platform=linux/amd64 ghcr.io/open-webui/open-webui:v0.10.2
COPY config/teams-auth.html /app/build/teams-auth.html
COPY docs/genie-setup-manual.html /app/build/docs/genie-setup-manual.html
COPY screenshots/ /app/build/screenshots/
